items:
  # Woods
  minecraft:oak_log: 12.00
  minecraft:spruce_log: 12.00
  minecraft:birch_log: 12.00
  minecraft:jungle_log: 12.00
  minecraft:acacia_log: 12.00
  minecraft:dark_oak_log: 12.00
  minecraft:mangrove_log: 14.00
  minecraft:cherry_log: 14.00
  minecraft:pale_oak_log: 14.00
  minecraft:crimson_stem: 14.00
  minecraft:warped_stem: 14.00
  minecraft:stripped_oak_log: 13.00
  minecraft:stripped_spruce_log: 13.00
  minecraft:stripped_birch_log: 13.00
  minecraft:stripped_jungle_log: 13.00
  minecraft:stripped_acacia_log: 13.00
  minecraft:stripped_dark_oak_log: 13.00
  minecraft:stripped_mangrove_log: 15.00
  minecraft:stripped_cherry_log: 15.00
  minecraft:stripped_pale_oak_log: 15.00
  minecraft:stripped_crimson_stem: 15.00
  minecraft:stripped_warped_stem: 15.00
  minecraft:mangrove_roots: 2.00
  minecraft:muddy_mangrove_roots: 1.50
  minecraft:oak_leaves: 1.00
  minecraft:spruce_leaves: 1.00
  minecraft:birch_leaves: 1.00
  minecraft:jungle_leaves: 1.00
  minecraft:acacia_leaves: 1.00
  minecraft:dark_oak_leaves: 1.00
  minecraft:mangrove_leaves: 1.00
  minecraft:cherry_leaves: 1.00
  minecraft:pale_oak_leaves: 1.00
  minecraft:azalea_leaves: 1.00
  minecraft:flowering_azalea_leaves: 1.25
  minecraft:oak_sapling: 2.00
  minecraft:spruce_sapling: 2.00
  minecraft:birch_sapling: 2.00
  minecraft:jungle_sapling: 2.00
  minecraft:acacia_sapling: 2.00
  minecraft:dark_oak_sapling: 2.00
  minecraft:mangrove_propagule: 2.00
  minecraft:cherry_sapling: 2.00
  minecraft:pale_oak_sapling: 2.00
  minecraft:azalea: 2.00
  minecraft:flowering_azalea: 2.25

  # Terrain Stone
  minecraft:dirt: 1.50
  minecraft:coarse_dirt: 1.75
  minecraft:rooted_dirt: 1.75
  minecraft:grass_block: 2.00
  minecraft:podzol: 2.50
  minecraft:mycelium: 5.00
  minecraft:cobblestone: 2.00
  minecraft:stone: 2.50
  minecraft:deepslate: 2.50
  minecraft:cobbled_deepslate: 2.00
  minecraft:sand: 4.00
  minecraft:red_sand: 4.50
  minecraft:gravel: 4.00
  minecraft:ice: 8.00
  minecraft:packed_ice: 24.00
  minecraft:blue_ice: 72.00
  minecraft:calcite: 2.50
  minecraft:tuff: 1.50
  minecraft:andesite: 2.50
  minecraft:diorite: 2.50
  minecraft:granite: 2.50
  minecraft:mud: 2.00
  minecraft:moss_block: 2.50
  minecraft:pale_moss_block: 2.50
  minecraft:pointed_dripstone: 2.00
  minecraft:dripstone_block: 2.50
  minecraft:obsidian: 32.00
  minecraft:crying_obsidian: 48.00
  minecraft:sponge: 12.00
  minecraft:wet_sponge: 12.00
  minecraft:blackstone: 2.50
  minecraft:basalt: 1.50
  minecraft:end_stone: 6.00

  # Nether
  minecraft:netherrack: 2.50
  minecraft:soul_sand: 4.00
  minecraft:soul_soil: 4.00
  minecraft:glowstone_dust: 4.00
  minecraft:quartz: 8.00
  minecraft:nether_wart: 5.00
  minecraft:crimson_fungus: 4.00
  minecraft:warped_fungus: 4.00
  minecraft:crimson_roots: 1.00
  minecraft:warped_roots: 1.00
  minecraft:nether_sprouts: 1.00
  minecraft:weeping_vines: 3.00
  minecraft:twisting_vines: 3.00
  minecraft:shroomlight: 10.00

  # Farming Plants
  minecraft:wheat: 3.00
  minecraft:carrot: 3.00
  minecraft:potato: 3.00
  minecraft:beetroot: 3.00
  minecraft:melon_slice: 2.00
  minecraft:pumpkin: 8.00
  minecraft:sugar_cane: 3.00
  minecraft:bamboo: 2.00
  minecraft:cactus: 2.50
  minecraft:kelp: 2.00
  minecraft:cocoa_beans: 3.00
  minecraft:sweet_berries: 4.00
  minecraft:glow_berries: 4.00
  minecraft:sea_pickle: 3.00
  minecraft:vine: 2.00
  minecraft:glow_lichen: 3.00
  minecraft:lily_pad: 3.00
  minecraft:brown_mushroom: 3.00
  minecraft:red_mushroom: 3.00
  minecraft:hanging_roots: 1.00
  minecraft:pale_hanging_moss: 1.00
  minecraft:beetroot_seeds: 1.00
  minecraft:melon_seeds: 2.00
  minecraft:pumpkin_seeds: 2.00
  minecraft:wheat_seeds: 1.00
  minecraft:torchflower_seeds: 1.00
  minecraft:pitcher_pod: 1.00

  # Food
  minecraft:apple: 3.50
  minecraft:egg: 1.50
  minecraft:beef: 4.00
  minecraft:chicken: 4.00
  minecraft:cod: 4.00
  minecraft:mutton: 4.00
  minecraft:porkchop: 4.00
  minecraft:rabbit: 4.00
  minecraft:salmon: 4.00
  minecraft:pufferfish: 4.00
  minecraft:tropical_fish: 4.00
  minecraft:chorus_fruit: 4.00
  minecraft:poisonous_potato: 1.00
  minecraft:honey_bottle: 4.00
  minecraft:suspicious_stew: 6.00

  # Mob Drops
  minecraft:rotten_flesh: 2.00
  minecraft:bone: 3.00
  minecraft:string: 4.00
  minecraft:spider_eye: 6.00
  minecraft:feather: 1.50
  minecraft:leather: 4.00
  minecraft:rabbit_hide: 2.00
  minecraft:honeycomb: 6.00
  minecraft:ink_sac: 4.00
  minecraft:glow_ink_sac: 5.00
  minecraft:slime_ball: 8.00
  minecraft:blaze_rod: 12.00
  minecraft:breeze_rod: 14.00
  minecraft:shulker_shell: 18.00
  minecraft:gunpowder: 8.00
  minecraft:rabbit_foot: 12.00
  minecraft:ghast_tear: 18.00
  minecraft:phantom_membrane: 8.00
  minecraft:nautilus_shell: 10.00
  minecraft:ender_pearl: 18.00
  minecraft:turtle_egg: 12.00
  minecraft:turtle_scute: 2.00
  minecraft:armadillo_scute: 3.00
  minecraft:prismarine_shard: 4.00
  minecraft:prismarine_crystals: 6.00
  minecraft:beehive: 12.00
  minecraft:bee_nest: 12.00
  minecraft:ochre_froglight: 16.00
  minecraft:pearlescent_froglight: 16.00
  minecraft:verdant_froglight: 16.00
  minecraft:resin_clump: 2.00

  # Ores Minerals
  minecraft:coal: 6.00
  minecraft:charcoal: 6.00
  minecraft:redstone: 4.00
  minecraft:lapis_lazuli: 6.00
  minecraft:raw_iron: 14.00
  minecraft:iron_ingot: 18.00
  minecraft:raw_copper: 10.00
  minecraft:copper_ingot: 12.00
  minecraft:raw_gold: 18.00
  minecraft:gold_ingot: 24.00
  minecraft:diamond: 90.00
  minecraft:emerald: 75.00
  minecraft:amethyst_shard: 10.00
  minecraft:coal_ore: 6.00
  minecraft:deepslate_coal_ore: 6.50
  minecraft:iron_ore: 14.00
  minecraft:deepslate_iron_ore: 14.50
  minecraft:copper_ore: 10.00
  minecraft:deepslate_copper_ore: 10.50
  minecraft:gold_ore: 18.00
  minecraft:deepslate_gold_ore: 18.50
  minecraft:redstone_ore: 18.00
  minecraft:deepslate_redstone_ore: 18.50
  minecraft:lapis_ore: 24.00
  minecraft:deepslate_lapis_ore: 24.50
  minecraft:diamond_ore: 90.00
  minecraft:deepslate_diamond_ore: 90.50
  minecraft:emerald_ore: 75.00
  minecraft:deepslate_emerald_ore: 75.50
  minecraft:nether_gold_ore: 12.00
  minecraft:nether_quartz_ore: 8.00
  minecraft:ancient_debris: 240.00

  # Flowers Decoration
  minecraft:allium: 2.00
  minecraft:azure_bluet: 2.00
  minecraft:blue_orchid: 2.00
  minecraft:cornflower: 2.00
  minecraft:dandelion: 1.50
  minecraft:lilac: 2.50
  minecraft:lily_of_the_valley: 3.00
  minecraft:orange_tulip: 2.00
  minecraft:oxeye_daisy: 2.00
  minecraft:peony: 2.50
  minecraft:pink_petals: 2.00
  minecraft:pink_tulip: 2.00
  minecraft:pitcher_plant: 2.00
  minecraft:poppy: 1.50
  minecraft:red_tulip: 2.00
  minecraft:rose_bush: 2.50
  minecraft:spore_blossom: 4.00
  minecraft:sunflower: 2.50
  minecraft:torchflower: 2.00
  minecraft:white_tulip: 2.00
  minecraft:wither_rose: 25.00
  minecraft:chorus_flower: 12.00
  minecraft:wildflowers: 1.00
  minecraft:cactus_flower: 2.00
  minecraft:tube_coral_block: 3.00
  minecraft:brain_coral_block: 3.00
  minecraft:bubble_coral_block: 3.00
  minecraft:fire_coral_block: 3.00
  minecraft:horn_coral_block: 3.00
  minecraft:tube_coral: 2.00
  minecraft:brain_coral: 2.00
  minecraft:bubble_coral: 2.00
  minecraft:fire_coral: 2.00
  minecraft:horn_coral: 2.00
  minecraft:tube_coral_fan: 2.50
  minecraft:brain_coral_fan: 2.50
  minecraft:bubble_coral_fan: 2.50
  minecraft:fire_coral_fan: 2.50
  minecraft:horn_coral_fan: 2.50
  minecraft:dead_tube_coral_block: 1.00
  minecraft:dead_brain_coral_block: 1.00
  minecraft:dead_bubble_coral_block: 1.00
  minecraft:dead_fire_coral_block: 1.00
  minecraft:dead_horn_coral_block: 1.00
  minecraft:dead_tube_coral: 0.50
  minecraft:dead_brain_coral: 0.50
  minecraft:dead_bubble_coral: 0.50
  minecraft:dead_fire_coral: 0.50
  minecraft:dead_horn_coral: 0.50
  minecraft:dead_tube_coral_fan: 1.00
  minecraft:dead_brain_coral_fan: 1.00
  minecraft:dead_bubble_coral_fan: 1.00
  minecraft:dead_fire_coral_fan: 1.00
  minecraft:dead_horn_coral_fan: 1.00

  # Misc
  minecraft:snowball: 1.00
  minecraft:flint: 2.00
  minecraft:clay_ball: 2.50

layout:
  groups:
    woods:
      generated-category: WOODS
      item-keys:
        - "minecraft:mangrove_roots"
        - "minecraft:muddy_mangrove_roots"
        - "minecraft:azalea"
        - "minecraft:flowering_azalea"
      item-key-patterns:
        - "minecraft:*_log"
        - "minecraft:*_stem"
        - "minecraft:stripped_*"
        - "minecraft:*_leaves"
        - "minecraft:*_sapling"
        - "minecraft:*_propagule"

    stone:
      generated-category: STONE
      item-keys:
        - "minecraft:dirt"
        - "minecraft:coarse_dirt"
        - "minecraft:rooted_dirt"
        - "minecraft:grass_block"
        - "minecraft:podzol"
        - "minecraft:mycelium"
        - "minecraft:cobblestone"
        - "minecraft:stone"
        - "minecraft:deepslate"
        - "minecraft:cobbled_deepslate"
        - "minecraft:sand"
        - "minecraft:red_sand"
        - "minecraft:gravel"
        - "minecraft:ice"
        - "minecraft:packed_ice"
        - "minecraft:blue_ice"
        - "minecraft:calcite"
        - "minecraft:tuff"
        - "minecraft:andesite"
        - "minecraft:diorite"
        - "minecraft:granite"
        - "minecraft:mud"
        - "minecraft:moss_block"
        - "minecraft:pale_moss_block"
        - "minecraft:pointed_dripstone"
        - "minecraft:dripstone_block"
        - "minecraft:obsidian"
        - "minecraft:crying_obsidian"
        - "minecraft:sponge"
        - "minecraft:wet_sponge"
        - "minecraft:blackstone"
        - "minecraft:basalt"

    nether:
      generated-category: NETHER
      item-keys:
        - "minecraft:netherrack"
        - "minecraft:soul_sand"
        - "minecraft:soul_soil"
        - "minecraft:glowstone_dust"
        - "minecraft:quartz"
        - "minecraft:crimson_fungus"
        - "minecraft:warped_fungus"
        - "minecraft:crimson_roots"
        - "minecraft:warped_roots"
        - "minecraft:nether_sprouts"
        - "minecraft:weeping_vines"
        - "minecraft:twisting_vines"
        - "minecraft:shroomlight"

    end:
      generated-category: END
      item-keys:
        - "minecraft:end_stone"
        - "minecraft:chorus_fruit"
        - "minecraft:chorus_flower"

    redstone:
      generated-category: REDSTONE
      item-keys:
        - "minecraft:redstone"

    ores-and-minerals:
      generated-category: ORES_AND_MINERALS
      item-keys:
        - "minecraft:coal"
        - "minecraft:charcoal"
        - "minecraft:lapis_lazuli"
        - "minecraft:raw_iron"
        - "minecraft:iron_ingot"
        - "minecraft:raw_copper"
        - "minecraft:copper_ingot"
        - "minecraft:raw_gold"
        - "minecraft:gold_ingot"
        - "minecraft:diamond"
        - "minecraft:emerald"
        - "minecraft:amethyst_shard"
        - "minecraft:coal_ore"
        - "minecraft:deepslate_coal_ore"
        - "minecraft:iron_ore"
        - "minecraft:deepslate_iron_ore"
        - "minecraft:copper_ore"
        - "minecraft:deepslate_copper_ore"
        - "minecraft:gold_ore"
        - "minecraft:deepslate_gold_ore"
        - "minecraft:redstone_ore"
        - "minecraft:deepslate_redstone_ore"
        - "minecraft:lapis_ore"
        - "minecraft:deepslate_lapis_ore"
        - "minecraft:diamond_ore"
        - "minecraft:deepslate_diamond_ore"
        - "minecraft:emerald_ore"
        - "minecraft:deepslate_emerald_ore"
        - "minecraft:nether_gold_ore"
        - "minecraft:nether_quartz_ore"
        - "minecraft:ancient_debris"

    farming:
      generated-category: FARMING
      item-keys:
        - "minecraft:wheat"
        - "minecraft:carrot"
        - "minecraft:potato"
        - "minecraft:beetroot"
        - "minecraft:melon_slice"
        - "minecraft:pumpkin"
        - "minecraft:sugar_cane"
        - "minecraft:bamboo"
        - "minecraft:cactus"
        - "minecraft:kelp"
        - "minecraft:cocoa_beans"
        - "minecraft:sweet_berries"
        - "minecraft:glow_berries"
        - "minecraft:vine"
        - "minecraft:glow_lichen"
        - "minecraft:lily_pad"
        - "minecraft:brown_mushroom"
        - "minecraft:red_mushroom"
        - "minecraft:hanging_roots"
        - "minecraft:pale_hanging_moss"
        - "minecraft:nether_wart"
        - "minecraft:pitcher_pod"
      item-key-patterns:
        - "minecraft:*_seeds"

    food:
      generated-category: FOOD
      item-keys:
        - "minecraft:apple"
        - "minecraft:egg"
        - "minecraft:beef"
        - "minecraft:chicken"
        - "minecraft:cod"
        - "minecraft:mutton"
        - "minecraft:porkchop"
        - "minecraft:rabbit"
        - "minecraft:salmon"
        - "minecraft:pufferfish"
        - "minecraft:tropical_fish"
        - "minecraft:poisonous_potato"
        - "minecraft:honey_bottle"
        - "minecraft:suspicious_stew"

    mob-drops:
      generated-category: MOB_DROPS
      item-keys:
        - "minecraft:rotten_flesh"
        - "minecraft:bone"
        - "minecraft:string"
        - "minecraft:spider_eye"
        - "minecraft:feather"
        - "minecraft:leather"
        - "minecraft:rabbit_hide"
        - "minecraft:honeycomb"
        - "minecraft:ink_sac"
        - "minecraft:glow_ink_sac"
        - "minecraft:slime_ball"
        - "minecraft:blaze_rod"
        - "minecraft:breeze_rod"
        - "minecraft:shulker_shell"
        - "minecraft:gunpowder"
        - "minecraft:rabbit_foot"
        - "minecraft:ghast_tear"
        - "minecraft:phantom_membrane"
        - "minecraft:nautilus_shell"
        - "minecraft:ender_pearl"
        - "minecraft:turtle_egg"
        - "minecraft:turtle_scute"
        - "minecraft:armadillo_scute"
        - "minecraft:prismarine_shard"
        - "minecraft:prismarine_crystals"
        - "minecraft:resin_clump"

    decoration:
      generated-category: DECORATION
      item-keys:
        - "minecraft:sea_pickle"
        - "minecraft:beehive"
        - "minecraft:bee_nest"
        - "minecraft:ochre_froglight"
        - "minecraft:pearlescent_froglight"
        - "minecraft:verdant_froglight"
        - "minecraft:allium"
        - "minecraft:azure_bluet"
        - "minecraft:blue_orchid"
        - "minecraft:cornflower"
        - "minecraft:dandelion"
        - "minecraft:lilac"
        - "minecraft:lily_of_the_valley"
        - "minecraft:oxeye_daisy"
        - "minecraft:peony"
        - "minecraft:pink_petals"
        - "minecraft:pitcher_plant"
        - "minecraft:poppy"
        - "minecraft:rose_bush"
        - "minecraft:spore_blossom"
        - "minecraft:sunflower"
        - "minecraft:torchflower"
        - "minecraft:wither_rose"
        - "minecraft:wildflowers"
        - "minecraft:cactus_flower"
      item-key-patterns:
        - "minecraft:*_tulip"
        - "minecraft:*_coral"
        - "minecraft:*_coral_block"
        - "minecraft:*_coral_fan"
        - "minecraft:dead_*_coral"
        - "minecraft:dead_*_coral_block"
        - "minecraft:dead_*_coral_fan"

    misc:
      generated-category: MISC
      item-keys:
        - "minecraft:snowball"
        - "minecraft:flint"
        - "minecraft:clay_ball"
